# standard jekyll configuration

baseurl:   http://dbindel.github.com/ldoc

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md']
markdown: kramdown

# configuration required for some pages

domain: dbindel.github.com
title: LDoc home page 
author: David Bindel
email: bindel@cs.cornell.edu

# For "fork me on GitHub" tag

github:
  username: dbindel
